In [41]:
import pandas as pd
import numpy as np
import re
import html
import difflib
from textblob import TextBlob
from collections import Counter
import nltk
from nltk.corpus import words as nltk_words
import emoji
from tqdm import tqdm
import wordninja

In [42]:
pd.set_option('display.max_colwidth', None)

nltk.download('words')

tqdm.pandas()

[nltk_data] Downloading package words to
[nltk_data]     C:\Users\windown\AppData\Roaming\nltk_data...
[nltk_data]   Package words is already up-to-date!


# Load dữ liệu 

In [43]:
df_train = pd.read_csv('amazon_shoe_train.csv', encoding= 'utf-8', engine='python', encoding_errors='replace')
df_validation = pd.read_csv('amazon_shoe_test.csv', encoding= 'utf-8', engine='python', encoding_errors= 'replace')

In [ ]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90000 entries, 0 to 89999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   labels  90000 non-null  object
 1   text    89966 non-null  object
dtypes: object(2)
memory usage: 1.4+ MB


In [45]:
df_validation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   labels  10000 non-null  object
 1   text    9998 non-null   object
dtypes: object(2)
memory usage: 156.4+ KB


# Xóa các dòng dữ liệu trùng lặp, giữ lại dòng đầu tiên

In [46]:
df_train = df_train.drop_duplicates(subset=['text'], keep='first').reset_index(drop=True)
df_validation = df_validation.drop_duplicates(subset=['text'], keep='first').reset_index(drop=True)

In [47]:
df_train

labels  \
0      Positive   
1      Negative   
2      Negative   
3      Negative   
4       Neutral   
...         ...   
85072   Neutral   
85073  Positive   
85074  Negative   
85075  Negative   
85076  Positive   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            text  
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Good shoe for office work. They will scuff very easy so be aware.  
1      I have had the Patricia II wedge in black for about 1 year & wore them regularly in season.  When I saw the Patricia at a good price in navy (from 6pm), I purchased them because I thought they would fit just like my Patricia IIs.  I was wrong, and paid the price with return shipping that 6pm doesn't pay.<br /><br />The crocs website says that crocs aren't suppose to fit like other sandals - they are suppose to be looser & thus more comfortable - I normally wear an 8-1/2, so have now tried both an 8 & a 9 in the Patricia shoe (I have an 8 in the Patricia II).  The Patricia 9 swims on my feet & they would be a hazard to walk around in.  The size 8 fits my left foot (which is my wider foot) but is too narrow on my right foot.  When I placed the shoes sole to sole, I did notice a slight difference in the width, which, apparently, my foot notices too.  I can only conclude a manufacturing defect.  But, it is this shoe specifically or the form for this shoe? (others have written the shoe is narrow).<br /><br />Consequently, if you have a wider foot, order the Patricia II instead of this one & if you are a 1/2 size, order down, not up.  
2                                                                                                                                                                                                                                                                                                                          

In [48]:
print(df_train.info())
print('=' * 40)
print(df_validation.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85077 entries, 0 to 85076
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   labels  85077 non-null  object
 1   text    85076 non-null  object
dtypes: object(2)
memory usage: 1.3+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9739 entries, 0 to 9738
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   labels  9739 non-null   object
 1   text    9738 non-null   object
dtypes: object(2)
memory usage: 152.3+ KB
None


# Xóa các dòng không có đánh giá

In [49]:
df_train = df_train.dropna(subset= ['text']).reset_index(drop = True)
df_validation = df_validation.dropna(subset = ['text']).reset_index(drop = True)

In [50]:
print(df_train.info())
print('=' * 40)
print(df_validation.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85076 entries, 0 to 85075
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   labels  85076 non-null  object
 1   text    85076 non-null  object
dtypes: object(2)
memory usage: 1.3+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9738 entries, 0 to 9737
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   labels  9738 non-null   object
 1   text    9738 non-null   object
dtypes: object(2)
memory usage: 152.3+ KB
None


# Trích xuất các đánh giá có chứa url

In [ ]:
url_pattern = r'https?://\S+|www\.\S+'

df_with_links = df_train[df_train['text'].str.contains(url_pattern, case=False, na=False)]

df_with_links[['text']]

text
1538                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       

# Trích xuất các đánh giá có chứa kí tự @

In [52]:
mention_pattern = r'@[A-Za-z0-9_]+'

df_with_mentions = df_train[df_train['text'].str.contains(mention_pattern, na=False)]

df_with_mentions[['text']]

text
2173                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       

# Trích xuất các đánh giá chỉ gồm các emoji

In [53]:
def is_only_emoji(text):
    if pd.isna(text) or not isinstance(text, str):
        return False
    stripped = text.strip()
    if not stripped:
        return False
    return all(char in emoji.EMOJI_DATA for char in stripped)

In [54]:
emoji_only_df_train = df_train[df_train['text'].apply(is_only_emoji)].copy()
emoji_only_df_train

labels            text
2549   Positive              👌🏻
6623   Positive              👍🏼
7735    Neutral               👍
10315  Positive               😊
13231  Positive              👍🏻
14118  Positive               💘
16529  Positive               👌
27153   Neutral              👍🏿
28473  Positive         👍👍👍👍👍👍👍
32662  Positive               😍
32745  Negative  👎🏻👎🏻👎🏻👎🏻👎🏻👎🏻👎🏻
41357  Positive             😊👌👍
41660   Neutral               😔
44629  Positive              💯👍
45594  Positive             😊👍🏻
49595  Positive      😃😃😄👌🏼👌🏼👌🏼💯
54189  Positive      👍🏾👍🏾👍🏾👍🏾👍🏾
57630  Negative          👎👎👎👎👎👎
58333  Positive             👍👍👍
61813  Negative              👎👎
66745  Negative               😆
67313  Positive              😊😊
70582  Negative               😞
74857  Positive          👌🏾👌🏾🙌🏾
78864   Neutral            😘😘😘😘
82285  Positive               😀

# Kiểm tra các từ viết tắt hoặc tiếng lóng (Slang)

In [55]:
english_vocab = set(w.lower() for w in nltk_words.words())

all_words = []

for text in df_train['text']:
    words_in_text = str(text).lower().split()
    all_words.extend(words_in_text)

tokens = [word for word in all_words if word.isalpha()]

word_freq = Counter(tokens)

In [56]:
suspected_slang = [
    word for word in word_freq
    if word not in english_vocab and word_freq[word] > 10
]

suspected_slang = sorted(suspected_slang, key=lambda x: -word_freq[x])
print(len(suspected_slang))

1291


In [57]:
for word in suspected_slang[:2000]:
        print(f"{word}: {word_freq[word]}")

shoes: 22123
feet: 7145
has: 4236
looks: 2663
sandals: 2312
toes: 2217
fits: 2127
purchased: 2121
larger: 1941
expected: 1921
straps: 1856
months: 1847
loved: 1842
started: 1602
pairs: 1588
wanted: 1573
looked: 1568
loves: 1511
years: 1493
seems: 1391
hours: 1364
returning: 1340
makes: 1337
reviews: 1317
buying: 1251
ones: 1167
feels: 1106
runs: 1087
liked: 1041
needed: 1016
stars: 997
weeks: 994
sunglasses: 993
socks: 992
wears: 970
arrived: 951
having: 884
lenses: 873
hoping: 871
heels: 830
wider: 826
seemed: 791
lasted: 763
laces: 755
using: 744
flops: 732
ordering: 706
blisters: 679
velcro: 647
paid: 606
slippers: 601
says: 589
compliments: 589
insoles: 565
things: 556
others: 541
sneakers: 537
noticed: 528
asics: 524
hiking: 510
compared: 503
owned: 469
crocs: 444
minutes: 437
online: 416
gets: 407
pleased: 405
held: 393
ripped: 384
walked: 380
footbed: 380
expecting: 370
problems: 370
inserts: 360
surprised: 358
clarks: 353
likes: 353
issues: 350
okay: 349
stretched: 344
nike: 33

# Định nghĩa các dictionaries cho ánh xạ

## Mapping cho các từ ngữ thô tục

In [58]:
profanity_map = {
    r'\bf[\W_]*[u@*#!]+[\W_]*c[\W_]*k[\w]*\b': 'fuck',
    r'\bf[\W_]*[@]+[\W_]*c[\W_]*h[\w]*\b': 'fuck',    
    r'\bs[\W_]*h[\W_]*[i1!*]+[\W_]*t[\w]*\b': 'shit',
    r'\bb[\W_]*[i1l!*@/]?[\W_]*t[\W_]*c[\W_]*h[\w]*\b': 'bitch',
    r'\ba[\W_]*s[\W_]*s[\W_]*h[\W_]*o[\W_]*l[\W_]*e[\w]*\b': 'asshole',
    r'\bp[\W_]*i[\W_]*s[\W_]*s[\w]*\b': 'piss',
    r'\b[a@]+[\W_]*[s$]+[\W_]*[s$]+[\w]*\b': 'ass',
    r'\bc[\W_]*r[\W_]*[@]+[\W_]*p[\w]*\b': 'crap',
    r'\bb[\W_]*[i1l!*@/]+[\W_]*t[\W_]*c[\W_]*h[\W_]*e[\W_]*s[\w]*\b': 'bitch',
}

## Mapping cho các emoji

In [59]:
emoji_adjective_map = {
    # Positive emotions
    "👍": "satisfied", "👍🏻": "satisfied", "👍🏼": "satisfied", "👍🏽": "satisfied", "👍🏾": "satisfied", "👍🏿": "satisfied",
    "😊": "happy", "😃": "joyful", "😀": "cheerful", "😄": "delighted",
    "😍": "in_love", "😘": "affectionate", "💘": "romantic",
    "👌": "perfect", "👌🏻": "perfect", "👌🏼": "perfect", "👌🏾": "perfect",
    "💯": "excellent", "🙌🏾": "excited", "😆": 'excited',

    # Negative emotions
    "👎": "disappointed", "👎🏻": "disappointed",
    "😔": "sad", "😞": "discouraged",
}

## Mapping cho các từ viết tắt, tiếng lóng

In [60]:
slang_dict = {
    "bc": "because",
    "ive": "i have",
    "lol": "laughing out loud",
    "lil": "little",
    "cuz": "because",
    "uv": "ultraviolet",
    "nyc": "new york city",
    "ur": "your",
    "luv": "love",
    "idk": "i do not know",
    "iam": "i am",
    "gf": "girlfriend",
    "ny": "new york",
    "omg": "oh my god",
    "fav": "favorite",
    "wtf": "what the fuck",
    "br": "but really",
    "ck": "check",
    "dr": "doctor",
    "btw": "by the way",
    "f@ch": "fuck",
    # Additional
    "ft": "feet",
    "qc": "quality control",
    "hrs": "hours",
    "vs": "versus",
    "sz": "size",
    "def": "definitely",
    "info": "information",
    "xl": "extra large",
    "ww": "wide width",
    "pros": "advantages",
    "cons": "disadvantages",
    
    # "wth": "what the hell", "wth": "with" # cái này t không biết làm sao để phân loại tốt 

    "dont": "do not", "don't": "do not",
    "doesnt": "does not", "doesn't": "does not",
    "didnt": "did not", "didn't": "did not",
    "cant": "cannot", "can't": "cannot",
    "couldnt": "could not", "couldn't": "could not",
    "shouldnt": "should not", "shouldn't": "should not",
    "wouldnt": "would not", "wouldn't": "would not",
    "wasnt": "was not", "wasn't": "was not",
    "isnt": "is not", "isn't": "is not",
    "arent": "are not", "aren't": "are not",
    "wont": "will not", "won't": "will not",
    "havent": "have not", "haven't": "have not",
    "hasnt": "has not", "hasn't": "has not",
    "hadnt": "had not", "hadn't": "had not",
    "neednt": "need not", "needn't": "need not",
    "mightnt": "might not", "mightn't": "might not",
    "mustnt": "must not", "mustn't": "must not",
    "shant": "shall not", "shan't": "shall not",
    "there's": "there is", "theres": "there is",
    "that's": "that is", "thats": "that is",
    
    "im": "i am", "i'm": "i am",
    "youre": "you are", "you're": "you are",
    "hes": "he is", "he's": "he is",
    "shes": "she is", "she's": "she is",
    "theyre": "they are", "they're": "they are",
    "its": "it is", "it's": "it is",
    "we're": "we are", "were": "we are",
    "thats": "that is", "that's": "that is",
    "whos": "who is", "who's": "who is",
}

# Định nghĩa các hàm cho các bước tiền xử lý

## Hàm sửa lỗi chính tả

In [61]:
ignore_words = {'crap', 'crappy'}

def correct_spelling(text):
    corrected_words = []
    for word in text.split():
        if word in ignore_words:
            corrected_words.append(word)  # giữ nguyên
        else:
            corrected_words.append(str(TextBlob(word).correct()))
    return " ".join(corrected_words)

## Hàm chuẩn hóa các dấu nháy về cùng một dạng

* Chuyển các dấu ’, `, ‘ về cùng một dấu là '

In [62]:
def normalize_quotes(text):
    return text.replace("’", "'").replace("`", "'").replace("‘", "'")

## Hàm chỉnh sửa giá trị phân số về thập phân

* Trong các đánh giá về giày thường có chỉ số về size, và đánh giá thường để chỉ số 1/2 thay vì 0.5
* Hàm này dùng để chuyển các giá trị phân số về giá trị thập phân

In [63]:
def convert_fractional_sizes(text):
    text = re.sub(r'(\d+)\s*1/2', lambda m: str(float(m.group(1)) + 0.5), text)
    text = re.sub(r'\b1/2\b', '0.5', text)
    return text

## Hàm loại bỏ các thành phần chưa xử lý từ HTML

* Các giá trị vừa gồm số và kí tự như @#34;... không có giá trị cho phân tích sẽ bị loại bỏ
* Các thẻ của HTML cũng được loại bỏ $\text{<br/>}$, $\text{<p>}$

In [64]:
def remove_html_tags_and_entities(text):
    text = re.sub(r'<.*?>', ' ', text)
    text = re.sub(r'&#\d{2,4};', '', text)
    return text

## Hàm loại bỏ các chuỗi dài vừa có số vừa có kí tự

* Xóa các chuỗi dài, chứa cả số và kí tự
* Các chuỗi này thường là mã video, mã sản phẩm

In [65]:
def remove_custom_tags(text):
    return re.sub(r'\[\[.*?\]\]', '', text, flags=re.IGNORECASE)

## Hàm chuyển thành chữ thường và phân tách

In [66]:
def lowercase_and_strip(text):
    return text.lower().strip()

## Hàm hiển thị các từ ngữ thô tục thay vì các dấu *** 

In [67]:
def uncensor_profanity(text):
    for pattern, replacement in profanity_map.items():
        text = re.sub(pattern, replacement, text, flags=re.IGNORECASE)
    return text

## Hàm thay thế emoji bằng các tính từ tương ứng

In [68]:
def replace_emoji(text):
    for emoji, adjective in emoji_adjective_map.items():
        text = text.replace(emoji, f" {adjective} ")
    return re.sub(r'\s+', ' ', text).strip()

## Hàm xóa các email

In [69]:
def remove_emails(text):
    return re.sub(r'\b[\w\.-]+@[\w\.-]+\.\w{2,4}\b', '', text)

## Hàm chuẩn hóa năm

* 1 yr old -> 1 year old
* yr -> year

In [70]:
def normalize_age(text):
    text = re.sub(r'(\d+)\s*yr[\.\- ]?old', r'\1 year old', text, flags=re.IGNORECASE)
    return re.sub(r'\byr\b', 'year', text)

## Hàm thay thế các từ viết tắt, từ lóng

In [71]:
def expand_slang_fuzzy(text):
    words = re.findall(r"\b\w+'\w+|\w+\b", text.lower())
    new_words = []

    for i, word in enumerate(words):
        if word == "u":
            if i > 0 and words[i - 1] == "the":
                new_words.append("u")
            else:
                new_words.append("you")
        elif word in slang_dict:
            new_words.append(slang_dict[word])
        else:
            # Fuzzy match if not in dictionary
            close_matches = difflib.get_close_matches(word, slang_dict.keys(), n=1, cutoff=0.8)
            if close_matches:
                new_words.append(slang_dict[close_matches[0]])
            else:
                new_words.append(word)

    return " ".join(new_words)

## Hàm lọc và giữ lại các kí tự là chữ, số và dấu chấm câu

In [72]:
def keep_only_text_numbers_dots(text):
    return re.sub(r"[^a-zA-Z0-9\.]", " ", text)

## Hàm chuẩn hóa khoảng trắng, xóa khoảng trắng và nối lại các từ tạo thành câu gọn gàng

In [73]:
def clean_whitespace(text):
    return " ".join(text.split())

## Hàm giảm các chữ lặp nhiều trong từ

In [74]:
def reduce_repeated_chars(text):
    return re.sub(r'(.)\1{2,}+', r'\1', text) # nếu chữ nào từ 3 lần lặp trở lên thì sẽ giảm xuống còn 1

## Hàm loại bỏ mã tracking / chuỗi khả nghi (dài >6, chứa cả số và chữ, không có khoảng trắng)

In [75]:
def remove_long_word(text):
    return re.sub(r'\b(?=\w*[a-zA-Z])(?=\w*\d)\w{7,}\b', '', text)

In [76]:
text = "this it is the thanking 1zrx2711yw12180891 hello gentlemen have not a problem with a package that is sent me it is with the direction i was not i am to send me this new direction please was not hello gentlemen have not a problem with speakers that is i bought my intesan much and would not like to call up and send it is to me this new direction mimi 4406 n w 74 ave mimi florida 33166"
print(remove_long_word(text))

this it is the thanking  hello gentlemen have not a problem with a package that is sent me it is with the direction i was not i am to send me this new direction please was not hello gentlemen have not a problem with speakers that is i bought my intesan much and would not like to call up and send it is to me this new direction mimi 4406 n w 74 ave mimi florida 33166


## Hàm loại bỏ số điện thoại

In [77]:
def remove_phone(text):
    return re.sub(r'(\+?\d{1,2}\s?)?(\(?\d{3}\)?[\s\-\.]?)?\d{3}[\s\-\.]?\d{4}\b', '', text)

# Module tổng tiền xử lý

In [ ]:
def clean_text(text):
    text = html.unescape(text)

    text = normalize_quotes(text)

    text = remove_custom_tags(text)

    text = lowercase_and_strip(text)

    text = uncensor_profanity(text)

    text = expand_slang_fuzzy(text)

    text = remove_html_tags_and_entities(text)

    text = convert_fractional_sizes(text) 

    text = remove_emails(text)

    text = normalize_age(text)
    
    text = replace_emoji(text)

    text = reduce_repeated_chars(text)

    text = remove_long_word(text)

    text = remove_phone(text)

    text = keep_only_text_numbers_dots(text)

    text = clean_whitespace(text)
    
    text = correct_spelling(text)

    return text

In [79]:
df_train['cleaned_text'] = df_train['text'].progress_apply(clean_text)

  0%|          | 0/85076 [00:00<?, ?it/s]

100%|██████████| 85076/85076 [2:54:44<00:00,  8.11it/s]   


In [80]:
df_validation['cleaned_text'] = df_validation['text'].progress_apply(clean_text)

100%|██████████| 9738/9738 [15:53<00:00, 10.21it/s]  


In [81]:
df_train = df_train.drop(columns=['text'])
df_validation = df_validation.drop(columns= ['text'])

In [82]:
pd.DataFrame(df_train).to_csv('after_clean_train.csv', index= False)
pd.DataFrame(df_validation).to_csv('after_clean_test.csv', index= False)

# Tìm kiếm các từ có độ dài bất thường, lớn hơn threshold

## Threshold = 18

In [103]:
def contains_long_word(text, threshold=12):
    if pd.isna(text):
        return False
    # Tách các từ, kiểm tra độ dài
    return any(len(word) > threshold for word in text.split())

In [104]:
df_long_words = df_train[df_train['cleaned_text'].apply(lambda x: contains_long_word(x, threshold=18))]

In [105]:
df_long_words[['cleaned_text']].head(50)

cleaned_text
53566  i saw this specific pair of balcony women s adhesion 8 running shoe advertised on facebook two weeks ago i had been searching for a running shoe that is had arch support and heel adding because i have not a heel spur that is just started bothering me anyway my mother in law got them for me for my with birthday i love how they are look and especially love how they are feel on my feet myfirstpairofsauconyshoes

### Sửa mẫu có độ dài token lớn hơn 18

* Index: 53566
* Sample trước khi chỉnh sửa: i saw this specific pair of balcony women s adhesion 8 running shoe advertised on facebook two weeks ago i had been searching for a running shoe that is had arch support and heel adding because i have not a heel spur that is just started bothering me anyway my mother in law got them for me for my with birthday i love how they are look and especially love how they are feel on my feet myfirstpairofsauconyshoes
* Sample sau khi chỉnh sửa: i saw this specific pair of balcony women s adhesion 8 running shoe advertised on facebook two weeks ago i had been searching for a running shoe that is had arch support and heel adding because i have not a heel spur that is just started bothering me anyway my mother in law got them for me for my with birthday i love how they are look and especially love how they are feel on my feet my first pair of saucony shoes

In [111]:
index_to_fix = 53566
df_train.at[index_to_fix, 'cleaned_text'] = df_train.at[index_to_fix, 'cleaned_text'].replace(
    'myfirstpairofsauconyshoes', 'my first pair of saucony shoes'
)

In [112]:
df_train.loc[index_to_fix]

labels                                                                                                                                                                                                                                                                                                                                                                                                                                  Positive
cleaned_text    i saw this specific pair of balcony women s adhesion 8 running shoe advertised on facebook two weeks ago i had been searching for a running shoe that is had arch support and heel adding because i have not a heel spur that is just started bothering me anyway my mother in law got them for me for my with birthday i love how they are look and especially love how they are feel on my feet my first pair of saucony shoes
Name: 53566, dtype: object

## Threshold = 15

In [98]:
df_long_words = df_train[df_train['cleaned_text'].apply(lambda x: contains_long_word(x, threshold=15))]

In [ ]:
index_to_fix_15 = []

In [99]:
df_long_words

labels  \
140    Negative   
1093   Negative   
2866   Negative   
4997   Positive   
5497   Positive   
8684   Positive   
10057  Negative   
20110  Negative   
20271   Neutral   
20777  Positive   
23244   Neutral   
23368   Neutral   
24281   Neutral   
24536  Negative   
30826  Positive   
31434  Negative   
31583  Negative   
32147  Negative   
32844   Neutral   
34777  Negative   
42185  Negative   
43819  Positive   
45072  Negative   
46833   Neutral   
47259   Neutral   
48446  Negative   
53566  Positive   
56305  Positive   
57102   Neutral   
58194  Positive   
59875  Positive   
60409  Negative   
62935  Negative   
67379  Positive   
69713  Negative   
69864  Negative   
71246  Negative   
75824  Positive   
81603  Negative   
84359  Positive   
84540  Positive   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          

### Các cụm cần sửa

* Index: 140  | getmyfactsstraight -> get my facts straight 
* Index: 4997 | supercute -> super cute, supercomfortable -> super comfortable
* Index: 10057| completlydifferent -> completely different
* Index: 20110| apparentlysomewhat -> apparently somewhat
* Index: 20777| plantarfasciitis -> plantar fasciitis
* Index: 34777| uncomfortability -> uncomfortableness
* Index: 62935| http wide width amazon com up bag details red bag m is i have utf sin isamazonfulfilled 0 scab -> Delete
* Index: 69713| itemswerenotshoes -> items were not shoes
* Index: 71246| notificacionescps -> notifications
* Index: 75824| quitecomfortable -> quite comfortable
* Index: 81603| consumerwarranty -> consumer warranty

In [117]:
replacements = {
    140: "getmyfactsstraight -> get my facts straight",
    4997: "supercute -> super cute, supercomfortable -> super comfortable",
    10057: "completlydifferent -> completely different",
    20110: "apparentlysomewhat -> apparently somewhat",
    20777: "plantarfasciitis -> plantar fasciitis",
    34777: "uncomfortability -> uncomfortableness",
    62935: "http wide width amazon com up bag details red bag m is i have utf sin isamazonfulfilled 0 scab -> Delete",
    69713: "itemswerenotshoes -> items were not shoes",
    71246: "notificacionescps -> notifications",
    75824: "quitecomfortable -> quite comfortable",
    81603: "consumerwarranty -> consumer warranty"
}

In [118]:
def apply_replacement(df, replacements):
    for idx, repl in replacements.items():
        if pd.isna(df.at[idx, 'cleaned_text']):
            continue  # bỏ qua nếu dòng đó rỗng

        pairs = [s.strip() for s in repl.split(',')]
        text = df.at[idx, 'cleaned_text']
        for pair in pairs:
            if '->' in pair:
                old, new = [s.strip() for s in pair.split('->')]
                if new.lower() == 'delete':
                    text = text.replace(old, '')  # Xóa cụm từ
                else:
                    text = text.replace(old, new)
        df.at[idx, 'cleaned_text'] = text

    return df

In [119]:
df_train = apply_replacement(df_train, replacements)

In [120]:
df_long_words = df_train[df_train['cleaned_text'].apply(lambda x: contains_long_word(x, threshold=15))]
df_long_words

labels  \
1093   Negative   
2866   Negative   
5497   Positive   
8684   Positive   
20271   Neutral   
23244   Neutral   
23368   Neutral   
24281   Neutral   
24536  Negative   
30826  Positive   
31434  Negative   
31583  Negative   
32147  Negative   
32844   Neutral   
34777  Negative   
42185  Negative   
43819  Positive   
45072  Negative   
46833   Neutral   
47259   Neutral   
48446  Negative   
56305  Positive   
57102   Neutral   
58194  Positive   
59875  Positive   
60409  Negative   
67379  Positive   
69864  Negative   
84359  Positive   
84540  Positive   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           

## Thực hiện tương tự trên tập test

In [124]:
df_long_words = df_validation[df_validation['cleaned_text'].apply(lambda x: contains_long_word(x, threshold=15))]
df_long_words

labels  \
362   Negative   
5170  Negative   
7904  Positive   

                                                                                                                                                                                                                                                                                                                                                                                                                                                  cleaned_text  
362                                                                                                                                                                                                                                                                                                                               not worth the headache of working with shoegistic i would not avoid them in the future and beware of their unprofessionalism  
5170  my first pair came from macysamazontfitcwas awesome i purchased this pair on a daily deal from amazon these she is do feet narrow which i like since i have not narrow feet but the she is i purchased from amazon are defective the right shoe it is overlay tight and has a knot inside the shoe that is it is not able to be removed this it is the third pair of defective she is that is i have not purchased from amazon definitely another return  
7904                                                                                                                                     they are really decent for the price not super top end nor would not you expect it is to be for the price but cheaper than anything on discountdancesupply and certainly cheaper than anything in person if you need not a basic class shoe that is does not run way too small and has free shipping this it is solid

In [125]:
index_to_fix = 5170

df_validation.at[5170, 'cleaned_text'] = df_validation.at[5170, 'cleaned_text'].replace(
    'macysamazontfitcwas', 'macys amazon fit was'
)

In [126]:
df_validation.loc[5170]

labels                                                                                                                                                                                                                                                                                                                                                                                                                                                           Negative
cleaned_text    my first pair came from macys amazon fit was awesome i purchased this pair on a daily deal from amazon these she is do feet narrow which i like since i have not narrow feet but the she is i purchased from amazon are defective the right shoe it is overlay tight and has a knot inside the shoe that is it is not able to be removed this it is the third pair of defective she is that is i have not purchased from amazon definitely another return
Name: 5170, dtype: object

# Loại bỏ các stopword theo đề xuất của nhóm

In [137]:
custom_stopwords = {
    # Đại từ cá nhân và sở hữu
    'i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves',
    'you', 'your', 'yours', 'yourself', 'yourselves',
    'he', 'him', 'his', 'himself',
    'she', 'her', 'hers', 'herself',
    'it', 'its', 'itself',
    'they', 'them', 'their', 'theirs', 'themselves',

    # Đại từ nghi vấn
    'what', 'which', 'who', 'whom', 'whose',

    # Mạo từ, giới từ
    'a', 'an', 'the', 'of', 'in', 'on', 'at', 'to', 'for', 'from', 'by',
    'with', 'about', 'as', 'into', 'through', 'over', 'under', 'above', 'below',
    'between', 'during', 'before', 'after', 'up', 'out', 

    # Từ nối, trạng từ không mang cảm xúc
    'and', 'or', 'but', 'if', 'while',
    'also', 'either', 'both', 'each', 'every', 'some', 'few', 'any',
    'this', 'that', 'these', 'those', 

    # Trợ động từ trung tính
    'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being',
    'do', 'does', 'did', 'doing',
    'have', 'has', 'had', 'having',
    'can', 'could', 'should', 'would', 'may', 'might', 'will',

    # Từ phụ trợ không mang giá trị nội dung
    'just', 'like', 'get', 'got', 'use', 'used', 'using',
    'still', 'ever',
    
    # Một số từ phụ thường lặp nhiều lần
    'one', 'two', 'three', 'also', 'etc'
}


In [138]:
def remove_custom_stopwords(text, stopwords_set):
    return ' '.join([word for word in text.split() if word.lower() not in stopwords_set])

In [139]:
df_train['no_stopwords'] = df_train['cleaned_text'].apply(lambda x: remove_custom_stopwords(x, custom_stopwords))
df_validation['no_stopwords'] = df_validation['cleaned_text'].apply(lambda x: remove_custom_stopwords(x, custom_stopwords))

In [140]:
df_train

labels  \
0      Positive   
1      Negative   
2      Negative   
3      Negative   
4       Neutral   
...         ...   
85071   Neutral   
85072  Positive   
85073  Negative   
85074  Negative   
85075  Positive   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     cleaned_text  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             good shoe for office work they are will stuff very easy so be aware   
1      i have not had the patrick ii wedge in black for about 1 year wore them regularly in season when i saw the patrick at a good price in navy from pm i purchased them because i thought they are would not feet just like my patrick his i was wrong and paid the price with return shipping that is pm does not pay but really but really the cross webster says that is cross are not suppose to feet like other scandals they are are suppose to be loose thus more comfortable i normally wear an 8 1 2 so have not now tried both an 8 a 9 in the patrick shoe i have not an 8 in the patrick ii the patrick 9 swims on my feet they are would not be a hazard to walk around in the size 8 it is my left foot which it is my wider foot but it is too narrow on my right foot when i placed the she is sole to sole i did notice a slight difference in the width which apparently my foot notices too i cannot only conclude a manufacturing defect but it is it is this shoe specifically or the form for this shoe there is have not written the shoe it is narrow but really but really consequently if you have not a wider foot order the patrick ii instead of this one if you are a 1 2 size order down not up   
2                                                                                                                                                                                                                    

In [141]:
df_train.to_csv('after_clean_train.csv', index=False)
df_validation.to_csv('after_clean_test.csv', index=False)